package zhangjie.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zhangjie.model.Buyer;
import zhangjie.model.BuyerExample;

public interface BuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    long countByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int deleteByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int deleteByPrimaryKey(Integer idBuyer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int insert(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int insertSelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    List<Buyer> selectByExample(BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    Buyer selectByPrimaryKey(Integer idBuyer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Buyer record, @Param("example") BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int updateByExample(@Param("record") Buyer record, @Param("example") BuyerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int updateByPrimaryKeySelective(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int updateByPrimaryKey(Buyer record);
}