package zhangjie.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zhangjie.model.Seller;
import zhangjie.model.SellerExample;

public interface SellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    long countByExample(SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int deleteByExample(SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int deleteByPrimaryKey(Integer idSeller);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int insert(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int insertSelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    List<Seller> selectByExample(SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    Seller selectByPrimaryKey(Integer idSeller);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Seller record, @Param("example") SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int updateByExample(@Param("record") Seller record, @Param("example") SellerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int updateByPrimaryKeySelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    int updateByPrimaryKey(Seller record);
}