package zhangjie.model;

import java.util.Date;

public class Bill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id_buyer
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    private Integer idBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id_commodity
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    private Integer idCommodity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id_seller
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    private Integer idSeller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.quantity
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.price
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.time
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.state
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.evaluation
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    private String evaluation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id
     *
     * @return the value of bill.id
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id
     *
     * @param id the value for bill.id
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id_buyer
     *
     * @return the value of bill.id_buyer
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public Integer getIdBuyer() {
        return idBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id_buyer
     *
     * @param idBuyer the value for bill.id_buyer
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public void setIdBuyer(Integer idBuyer) {
        this.idBuyer = idBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id_commodity
     *
     * @return the value of bill.id_commodity
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public Integer getIdCommodity() {
        return idCommodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id_commodity
     *
     * @param idCommodity the value for bill.id_commodity
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public void setIdCommodity(Integer idCommodity) {
        this.idCommodity = idCommodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id_seller
     *
     * @return the value of bill.id_seller
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public Integer getIdSeller() {
        return idSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id_seller
     *
     * @param idSeller the value for bill.id_seller
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public void setIdSeller(Integer idSeller) {
        this.idSeller = idSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.quantity
     *
     * @return the value of bill.quantity
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.quantity
     *
     * @param quantity the value for bill.quantity
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.price
     *
     * @return the value of bill.price
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.price
     *
     * @param price the value for bill.price
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.time
     *
     * @return the value of bill.time
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.time
     *
     * @param time the value for bill.time
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.state
     *
     * @return the value of bill.state
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.state
     *
     * @param state the value for bill.state
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.evaluation
     *
     * @return the value of bill.evaluation
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.evaluation
     *
     * @param evaluation the value for bill.evaluation
     *
     * @mbg.generated Fri Apr 12 09:06:57 CST 2019
     */
    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation == null ? null : evaluation.trim();
    }
}