package zhangjie.model;

import java.util.Date;

public class Bill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.account_buyer
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private String accountBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id_commodity
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private Integer idCommodity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.account_seller
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private String accountSeller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.quantity
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.price
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.time
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.state
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.evaluation_price
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private String evaluationPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.evaluation_service
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private String evaluationService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.evaluation
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    private String evaluation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id
     *
     * @return the value of bill.id
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id
     *
     * @param id the value for bill.id
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.account_buyer
     *
     * @return the value of bill.account_buyer
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public String getAccountBuyer() {
        return accountBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.account_buyer
     *
     * @param accountBuyer the value for bill.account_buyer
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setAccountBuyer(String accountBuyer) {
        this.accountBuyer = accountBuyer == null ? null : accountBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id_commodity
     *
     * @return the value of bill.id_commodity
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public Integer getIdCommodity() {
        return idCommodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id_commodity
     *
     * @param idCommodity the value for bill.id_commodity
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setIdCommodity(Integer idCommodity) {
        this.idCommodity = idCommodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.account_seller
     *
     * @return the value of bill.account_seller
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public String getAccountSeller() {
        return accountSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.account_seller
     *
     * @param accountSeller the value for bill.account_seller
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setAccountSeller(String accountSeller) {
        this.accountSeller = accountSeller == null ? null : accountSeller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.quantity
     *
     * @return the value of bill.quantity
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.quantity
     *
     * @param quantity the value for bill.quantity
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.price
     *
     * @return the value of bill.price
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.price
     *
     * @param price the value for bill.price
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.time
     *
     * @return the value of bill.time
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.time
     *
     * @param time the value for bill.time
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.state
     *
     * @return the value of bill.state
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.state
     *
     * @param state the value for bill.state
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.evaluation_price
     *
     * @return the value of bill.evaluation_price
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public String getEvaluationPrice() {
        return evaluationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.evaluation_price
     *
     * @param evaluationPrice the value for bill.evaluation_price
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setEvaluationPrice(String evaluationPrice) {
        this.evaluationPrice = evaluationPrice == null ? null : evaluationPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.evaluation_service
     *
     * @return the value of bill.evaluation_service
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public String getEvaluationService() {
        return evaluationService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.evaluation_service
     *
     * @param evaluationService the value for bill.evaluation_service
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setEvaluationService(String evaluationService) {
        this.evaluationService = evaluationService == null ? null : evaluationService.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.evaluation
     *
     * @return the value of bill.evaluation
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.evaluation
     *
     * @param evaluation the value for bill.evaluation
     *
     * @mbg.generated Wed Apr 17 10:37:38 CST 2019
     */
    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation == null ? null : evaluation.trim();
    }
}