package zhangjie.model;

import java.util.ArrayList;
import java.util.List;

public class BuyerExample extends BaseExample{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public BuyerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdBuyerIsNull() {
            addCriterion("id_buyer is null");
            return (Criteria) this;
        }

        public Criteria andIdBuyerIsNotNull() {
            addCriterion("id_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andIdBuyerEqualTo(Integer value) {
            addCriterion("id_buyer =", value, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andIdBuyerNotEqualTo(Integer value) {
            addCriterion("id_buyer <>", value, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andIdBuyerGreaterThan(Integer value) {
            addCriterion("id_buyer >", value, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andIdBuyerGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_buyer >=", value, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andIdBuyerLessThan(Integer value) {
            addCriterion("id_buyer <", value, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andIdBuyerLessThanOrEqualTo(Integer value) {
            addCriterion("id_buyer <=", value, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andIdBuyerIn(List<Integer> values) {
            addCriterion("id_buyer in", values, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andIdBuyerNotIn(List<Integer> values) {
            addCriterion("id_buyer not in", values, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andIdBuyerBetween(Integer value1, Integer value2) {
            addCriterion("id_buyer between", value1, value2, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andIdBuyerNotBetween(Integer value1, Integer value2) {
            addCriterion("id_buyer not between", value1, value2, "idBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerIsNull() {
            addCriterion("name_buyer is null");
            return (Criteria) this;
        }

        public Criteria andNameBuyerIsNotNull() {
            addCriterion("name_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andNameBuyerEqualTo(String value) {
            addCriterion("name_buyer =", value, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerNotEqualTo(String value) {
            addCriterion("name_buyer <>", value, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerGreaterThan(String value) {
            addCriterion("name_buyer >", value, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("name_buyer >=", value, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerLessThan(String value) {
            addCriterion("name_buyer <", value, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerLessThanOrEqualTo(String value) {
            addCriterion("name_buyer <=", value, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerLike(String value) {
            addCriterion("name_buyer like", value, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerNotLike(String value) {
            addCriterion("name_buyer not like", value, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerIn(List<String> values) {
            addCriterion("name_buyer in", values, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerNotIn(List<String> values) {
            addCriterion("name_buyer not in", values, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerBetween(String value1, String value2) {
            addCriterion("name_buyer between", value1, value2, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andNameBuyerNotBetween(String value1, String value2) {
            addCriterion("name_buyer not between", value1, value2, "nameBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerIsNull() {
            addCriterion("sex_buyer is null");
            return (Criteria) this;
        }

        public Criteria andSexBuyerIsNotNull() {
            addCriterion("sex_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andSexBuyerEqualTo(String value) {
            addCriterion("sex_buyer =", value, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerNotEqualTo(String value) {
            addCriterion("sex_buyer <>", value, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerGreaterThan(String value) {
            addCriterion("sex_buyer >", value, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("sex_buyer >=", value, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerLessThan(String value) {
            addCriterion("sex_buyer <", value, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerLessThanOrEqualTo(String value) {
            addCriterion("sex_buyer <=", value, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerLike(String value) {
            addCriterion("sex_buyer like", value, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerNotLike(String value) {
            addCriterion("sex_buyer not like", value, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerIn(List<String> values) {
            addCriterion("sex_buyer in", values, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerNotIn(List<String> values) {
            addCriterion("sex_buyer not in", values, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerBetween(String value1, String value2) {
            addCriterion("sex_buyer between", value1, value2, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andSexBuyerNotBetween(String value1, String value2) {
            addCriterion("sex_buyer not between", value1, value2, "sexBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerIsNull() {
            addCriterion("age_buyer is null");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerIsNotNull() {
            addCriterion("age_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerEqualTo(String value) {
            addCriterion("age_buyer =", value, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerNotEqualTo(String value) {
            addCriterion("age_buyer <>", value, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerGreaterThan(String value) {
            addCriterion("age_buyer >", value, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("age_buyer >=", value, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerLessThan(String value) {
            addCriterion("age_buyer <", value, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerLessThanOrEqualTo(String value) {
            addCriterion("age_buyer <=", value, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerLike(String value) {
            addCriterion("age_buyer like", value, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerNotLike(String value) {
            addCriterion("age_buyer not like", value, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerIn(List<String> values) {
            addCriterion("age_buyer in", values, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerNotIn(List<String> values) {
            addCriterion("age_buyer not in", values, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerBetween(String value1, String value2) {
            addCriterion("age_buyer between", value1, value2, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAgeBuyerNotBetween(String value1, String value2) {
            addCriterion("age_buyer not between", value1, value2, "ageBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerIsNull() {
            addCriterion("address_buyer is null");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerIsNotNull() {
            addCriterion("address_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerEqualTo(String value) {
            addCriterion("address_buyer =", value, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerNotEqualTo(String value) {
            addCriterion("address_buyer <>", value, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerGreaterThan(String value) {
            addCriterion("address_buyer >", value, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("address_buyer >=", value, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerLessThan(String value) {
            addCriterion("address_buyer <", value, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerLessThanOrEqualTo(String value) {
            addCriterion("address_buyer <=", value, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerLike(String value) {
            addCriterion("address_buyer like", value, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerNotLike(String value) {
            addCriterion("address_buyer not like", value, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerIn(List<String> values) {
            addCriterion("address_buyer in", values, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerNotIn(List<String> values) {
            addCriterion("address_buyer not in", values, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerBetween(String value1, String value2) {
            addCriterion("address_buyer between", value1, value2, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andAddressBuyerNotBetween(String value1, String value2) {
            addCriterion("address_buyer not between", value1, value2, "addressBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerIsNull() {
            addCriterion("past_history_buyer is null");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerIsNotNull() {
            addCriterion("past_history_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerEqualTo(String value) {
            addCriterion("past_history_buyer =", value, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerNotEqualTo(String value) {
            addCriterion("past_history_buyer <>", value, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerGreaterThan(String value) {
            addCriterion("past_history_buyer >", value, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("past_history_buyer >=", value, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerLessThan(String value) {
            addCriterion("past_history_buyer <", value, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerLessThanOrEqualTo(String value) {
            addCriterion("past_history_buyer <=", value, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerLike(String value) {
            addCriterion("past_history_buyer like", value, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerNotLike(String value) {
            addCriterion("past_history_buyer not like", value, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerIn(List<String> values) {
            addCriterion("past_history_buyer in", values, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerNotIn(List<String> values) {
            addCriterion("past_history_buyer not in", values, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerBetween(String value1, String value2) {
            addCriterion("past_history_buyer between", value1, value2, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andPastHistoryBuyerNotBetween(String value1, String value2) {
            addCriterion("past_history_buyer not between", value1, value2, "pastHistoryBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerIsNull() {
            addCriterion("child_name_buyer is null");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerIsNotNull() {
            addCriterion("child_name_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerEqualTo(String value) {
            addCriterion("child_name_buyer =", value, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerNotEqualTo(String value) {
            addCriterion("child_name_buyer <>", value, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerGreaterThan(String value) {
            addCriterion("child_name_buyer >", value, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("child_name_buyer >=", value, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerLessThan(String value) {
            addCriterion("child_name_buyer <", value, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerLessThanOrEqualTo(String value) {
            addCriterion("child_name_buyer <=", value, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerLike(String value) {
            addCriterion("child_name_buyer like", value, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerNotLike(String value) {
            addCriterion("child_name_buyer not like", value, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerIn(List<String> values) {
            addCriterion("child_name_buyer in", values, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerNotIn(List<String> values) {
            addCriterion("child_name_buyer not in", values, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerBetween(String value1, String value2) {
            addCriterion("child_name_buyer between", value1, value2, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildNameBuyerNotBetween(String value1, String value2) {
            addCriterion("child_name_buyer not between", value1, value2, "childNameBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerIsNull() {
            addCriterion("child_identity_buyer is null");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerIsNotNull() {
            addCriterion("child_identity_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerEqualTo(String value) {
            addCriterion("child_identity_buyer =", value, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerNotEqualTo(String value) {
            addCriterion("child_identity_buyer <>", value, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerGreaterThan(String value) {
            addCriterion("child_identity_buyer >", value, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("child_identity_buyer >=", value, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerLessThan(String value) {
            addCriterion("child_identity_buyer <", value, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerLessThanOrEqualTo(String value) {
            addCriterion("child_identity_buyer <=", value, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerLike(String value) {
            addCriterion("child_identity_buyer like", value, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerNotLike(String value) {
            addCriterion("child_identity_buyer not like", value, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerIn(List<String> values) {
            addCriterion("child_identity_buyer in", values, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerNotIn(List<String> values) {
            addCriterion("child_identity_buyer not in", values, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerBetween(String value1, String value2) {
            addCriterion("child_identity_buyer between", value1, value2, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildIdentityBuyerNotBetween(String value1, String value2) {
            addCriterion("child_identity_buyer not between", value1, value2, "childIdentityBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerIsNull() {
            addCriterion("child_phone_buyer is null");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerIsNotNull() {
            addCriterion("child_phone_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerEqualTo(String value) {
            addCriterion("child_phone_buyer =", value, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerNotEqualTo(String value) {
            addCriterion("child_phone_buyer <>", value, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerGreaterThan(String value) {
            addCriterion("child_phone_buyer >", value, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("child_phone_buyer >=", value, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerLessThan(String value) {
            addCriterion("child_phone_buyer <", value, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerLessThanOrEqualTo(String value) {
            addCriterion("child_phone_buyer <=", value, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerLike(String value) {
            addCriterion("child_phone_buyer like", value, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerNotLike(String value) {
            addCriterion("child_phone_buyer not like", value, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerIn(List<String> values) {
            addCriterion("child_phone_buyer in", values, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerNotIn(List<String> values) {
            addCriterion("child_phone_buyer not in", values, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerBetween(String value1, String value2) {
            addCriterion("child_phone_buyer between", value1, value2, "childPhoneBuyer");
            return (Criteria) this;
        }

        public Criteria andChildPhoneBuyerNotBetween(String value1, String value2) {
            addCriterion("child_phone_buyer not between", value1, value2, "childPhoneBuyer");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buyer
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 18 10:43:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}