package zhangjie.model;

public class Buyer{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.id_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private Integer idBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.name_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String nameBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.sex_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String sexBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.age_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String ageBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.address_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String addressBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.past_history_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String pastHistoryBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.child_name_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String childNameBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.child_identity_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String childIdentityBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buyer.child_phone_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String childPhoneBuyer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.id_buyer
     *
     * @return the value of buyer.id_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public Integer getIdBuyer() {
        return idBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.id_buyer
     *
     * @param idBuyer the value for buyer.id_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setIdBuyer(Integer idBuyer) {
        this.idBuyer = idBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.name_buyer
     *
     * @return the value of buyer.name_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getNameBuyer() {
        return nameBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.name_buyer
     *
     * @param nameBuyer the value for buyer.name_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setNameBuyer(String nameBuyer) {
        this.nameBuyer = nameBuyer == null ? null : nameBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.sex_buyer
     *
     * @return the value of buyer.sex_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getSexBuyer() {
        return sexBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.sex_buyer
     *
     * @param sexBuyer the value for buyer.sex_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setSexBuyer(String sexBuyer) {
        this.sexBuyer = sexBuyer == null ? null : sexBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.age_buyer
     *
     * @return the value of buyer.age_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getAgeBuyer() {
        return ageBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.age_buyer
     *
     * @param ageBuyer the value for buyer.age_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setAgeBuyer(String ageBuyer) {
        this.ageBuyer = ageBuyer == null ? null : ageBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.address_buyer
     *
     * @return the value of buyer.address_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getAddressBuyer() {
        return addressBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.address_buyer
     *
     * @param addressBuyer the value for buyer.address_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setAddressBuyer(String addressBuyer) {
        this.addressBuyer = addressBuyer == null ? null : addressBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.past_history_buyer
     *
     * @return the value of buyer.past_history_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getPastHistoryBuyer() {
        return pastHistoryBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.past_history_buyer
     *
     * @param pastHistoryBuyer the value for buyer.past_history_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setPastHistoryBuyer(String pastHistoryBuyer) {
        this.pastHistoryBuyer = pastHistoryBuyer == null ? null : pastHistoryBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.child_name_buyer
     *
     * @return the value of buyer.child_name_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getChildNameBuyer() {
        return childNameBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.child_name_buyer
     *
     * @param childNameBuyer the value for buyer.child_name_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setChildNameBuyer(String childNameBuyer) {
        this.childNameBuyer = childNameBuyer == null ? null : childNameBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.child_identity_buyer
     *
     * @return the value of buyer.child_identity_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getChildIdentityBuyer() {
        return childIdentityBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.child_identity_buyer
     *
     * @param childIdentityBuyer the value for buyer.child_identity_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setChildIdentityBuyer(String childIdentityBuyer) {
        this.childIdentityBuyer = childIdentityBuyer == null ? null : childIdentityBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buyer.child_phone_buyer
     *
     * @return the value of buyer.child_phone_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getChildPhoneBuyer() {
        return childPhoneBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buyer.child_phone_buyer
     *
     * @param childPhoneBuyer the value for buyer.child_phone_buyer
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setChildPhoneBuyer(String childPhoneBuyer) {
        this.childPhoneBuyer = childPhoneBuyer == null ? null : childPhoneBuyer.trim();
    }
}