package zhangjie.model;

public class Commodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.icon
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.name
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.price
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.category
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.business_name
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private String businessName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.characteristic
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private String characteristic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.sales_volume
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private Integer salesVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.evaluation_price
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private Double evaluationPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.evaluation_service
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private Double evaluationService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.shangjia
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    private String shangjia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.icon
     *
     * @return the value of commodity.icon
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.icon
     *
     * @param icon the value for commodity.icon
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.name
     *
     * @return the value of commodity.name
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.name
     *
     * @param name the value for commodity.name
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.price
     *
     * @return the value of commodity.price
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.price
     *
     * @param price the value for commodity.price
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.category
     *
     * @return the value of commodity.category
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.category
     *
     * @param category the value for commodity.category
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.business_name
     *
     * @return the value of commodity.business_name
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.business_name
     *
     * @param businessName the value for commodity.business_name
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.characteristic
     *
     * @return the value of commodity.characteristic
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public String getCharacteristic() {
        return characteristic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.characteristic
     *
     * @param characteristic the value for commodity.characteristic
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setCharacteristic(String characteristic) {
        this.characteristic = characteristic == null ? null : characteristic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.sales_volume
     *
     * @return the value of commodity.sales_volume
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public Integer getSalesVolume() {
        return salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.sales_volume
     *
     * @param salesVolume the value for commodity.sales_volume
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setSalesVolume(Integer salesVolume) {
        this.salesVolume = salesVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.evaluation_price
     *
     * @return the value of commodity.evaluation_price
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public Double getEvaluationPrice() {
        return evaluationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.evaluation_price
     *
     * @param evaluationPrice the value for commodity.evaluation_price
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setEvaluationPrice(Double evaluationPrice) {
        this.evaluationPrice = evaluationPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.evaluation_service
     *
     * @return the value of commodity.evaluation_service
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public Double getEvaluationService() {
        return evaluationService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.evaluation_service
     *
     * @param evaluationService the value for commodity.evaluation_service
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setEvaluationService(Double evaluationService) {
        this.evaluationService = evaluationService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.shangjia
     *
     * @return the value of commodity.shangjia
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public String getShangjia() {
        return shangjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.shangjia
     *
     * @param shangjia the value for commodity.shangjia
     *
     * @mbg.generated Sat Apr 27 14:51:51 CST 2019
     */
    public void setShangjia(String shangjia) {
        this.shangjia = shangjia == null ? null : shangjia.trim();
    }
}