package zhangjie.model;

public class Seller{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.id_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private Integer idSeller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.name_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String nameSeller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.address_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private String addressSeller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.good_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private Integer goodSeller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller.bad_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    private Integer badSeller;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.id_seller
     *
     * @return the value of seller.id_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public Integer getIdSeller() {
        return idSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.id_seller
     *
     * @param idSeller the value for seller.id_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setIdSeller(Integer idSeller) {
        this.idSeller = idSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.name_seller
     *
     * @return the value of seller.name_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getNameSeller() {
        return nameSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.name_seller
     *
     * @param nameSeller the value for seller.name_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setNameSeller(String nameSeller) {
        this.nameSeller = nameSeller == null ? null : nameSeller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.address_seller
     *
     * @return the value of seller.address_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public String getAddressSeller() {
        return addressSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.address_seller
     *
     * @param addressSeller the value for seller.address_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setAddressSeller(String addressSeller) {
        this.addressSeller = addressSeller == null ? null : addressSeller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.good_seller
     *
     * @return the value of seller.good_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public Integer getGoodSeller() {
        return goodSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.good_seller
     *
     * @param goodSeller the value for seller.good_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setGoodSeller(Integer goodSeller) {
        this.goodSeller = goodSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller.bad_seller
     *
     * @return the value of seller.bad_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public Integer getBadSeller() {
        return badSeller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller.bad_seller
     *
     * @param badSeller the value for seller.bad_seller
     *
     * @mbg.generated Mon Feb 18 10:43:23 CST 2019
     */
    public void setBadSeller(Integer badSeller) {
        this.badSeller = badSeller;
    }
}